npmScopes:
  xlabs-xyz:
    npmPublishRegistry: "https://registry.npmjs.org/"
    npmRegistryServer: "https://registry.npmjs.org/"

packageExtensions:
  "@ledgerhq/domain-service@1.4.1":
    dependencies:
      "@ledgerhq/types-cryptoassets": ^7.30.0
  "@ledgerhq/hw-transport-node-hid-noevents@6.30.14":
    dependencies:
      "@types/node-hid": ^1.3.4
  "@ledgerhq/types-live@6.89.0":
    dependencies:
      "@ledgerhq/types-cryptoassets": ^7.30.0
      "@ledgerhq/types-devices": ^6.27.0
      "@types/react": ^19.2.6
