npmScopes:
  xlabs-xyz:
    npmPublishRegistry: "https://registry.npmjs.org/"
    npmRegistryServer: "https://registry.npmjs.org/"

packageExtensions:
  "@ledgerhq/domain-service@1.6.3":
    dependencies:
      "@ledgerhq/types-cryptoassets": ^7.32.0
  "@ledgerhq/hw-transport-node-hid-noevents@6.31.0":
    dependencies:
      "@types/node-hid": ^1.3.4
  "@ledgerhq/types-live@6.96.0":
    dependencies:
      "@ledgerhq/types-cryptoassets": ^7.32.0
      "@ledgerhq/types-devices": ^6.28.0
      "@types/react": ^19.2.6
      "@ledgerhq/client-ids": ^0.5.1
