packageExtensions:
  "@ledgerhq/domain-service@1.1.21":
    dependencies:
      "@ledgerhq/types-cryptoassets": ^7.12.0
  "@ledgerhq/types-live@6.47.0":
    dependencies:
      "@ledgerhq/types-cryptoassets": ^7.12.0
      "@ledgerhq/types-devices": ^6.24.0
  "@ledgerhq/hw-transport-node-hid-noevents@6.29.6":
    dependencies:
      "@types/node-hid": ^1.3.4
